### ISSUE TITLE
won't accept an input JSON string which is larger 48 KB in size 

### ISSUE THREAD

**Issue by vhoanguyen** [buildingcash/json-to-markdown-table-action#84]
Error: An error occurred trying to start process '/home/runner/runners/2.311.0/externals/node16/bin/node' with working directory '/home/runner/work/github-access-management/github-access-management'. Argument list too long

**Comment by julienfouilhe** [comment]
Should be fixed in https://github.com/buildingcash/json-to-markdown-table-action/pull/103
